# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-05-13 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170506_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
